### ISSUE TITLE
qBittorrent sidebar text too dark.

### ISSUE THREAD

**Issue by tordenflesk** [themepark-dev/theme.park#527]
**Describe the bug**
https://i.imgur.com/2Gl17c5.png

**Theme Install Method** (Don't skip)
- Docker Compose:
```
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0-libtorrentv1
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Oslo
      - WEBUI_PORT=8090
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:qbittorrent-regex
      - TP_THEME=nord
    volumes:
      - /Docker_Config/QBITTORRENT:/config
      - /srv/dev-disk-by-uuid-5c3c71b2-dce8-4967-95f4-eba3d293a511/downloads:/downloads
      - /srv/dev-disk-by-uuid-5c3c71b2-dce8-4967-95f4-eba3d293a511:/DATA01
    ports:
      - 8090:8090
      - 32323:32323
      - 32323:32323/udp
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    mem_limit: 512m
    memswap_limit: 512m
```
