### ISSUE TITLE
Broken main menu navigation in Qbittorrent

### ISSUE THREAD

**Issue by IevgenSobko** [themepark-dev/theme.park#545]
**Describe the bug**
Broken main menu navigation in Qbittorrent

**Theme Install Method** (Don't skip)

```
version: "3.7"

services:
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "8083:8083"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Kiev
      - WEBUI_PORTS=8083/tcp,8083/udp
      - TP_HOTIO=true
      - TP_THEME=dracula
      - VPN_ENABLED=true
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=192.168.0.0/16,100.109.159.152/32,100.88.127.1/32,100.114.221.138/32
      - VPN_CONF=wg0
      - VPN_EXPOSE_PORTS_ON_LAN=4000/tcp # for curl
      - VPN_AUTO_PORT_FORWARD=true
      # - VPN_KEEP_LOCAL_DNS=false
      - PRIVOXY_ENABLED=false
    volumes:
      - /home/user/.docker/qbittorrent/theme-park-mods/98-themepark-qbittorrent:/etc/cont-init.d/98-themepark
      - /home/user/.docker/qbittorrent:/config
      - /home/user/.docker/qbittorrent/fake_data:/data
      - /mnt/HDD1/TorrentS:/downloads
      - /mnt/HDD14TB01:/mnt/HDD14TB01
    restart: always
```
Log about 500 lines so I used 
https://privatebin.net/?aee47b1b6e8e9891#76f9dkDBVZvsZ3TzrZFqfrGXH42SEe41NYsMkLGtsQbt

**Application Info** (Don't skip)
- Version : `4.6.3`
- Container: `image: ghcr.io/hotio/qbittorrent:release`
- Logs: https://privatebin.net/?aee47b1b6e8e9891#76f9dkDBVZvsZ3TzrZFqfrGXH42SEe41NYsMkLGtsQbt

**To Reproduce**
1. Open qbittorrent web UI in browser
2. Try to open any main menu item(I always find myself looking libtorrent version `Help` > `About` )
3. Once you start navigating to `About` menu will close
Tried original theme and navigation works. Also tried private widow mode and it didn't help.

**Expected behavior**
Easily accessible menu navigation
