### ISSUE TITLE
QbitTorrent - can't stop the torrents

### ISSUE THREAD

**Issue by bassterror** [themepark-dev/theme.park#551]
**Describe the bug**
When you hit "Pause/Stop" button, it doesn't stop the torrent and an error is thrown in the console:
`QMetaObject::invokeMethod: No such method TorrentsController::stopAction()`

**Theme Install Method** (Don't skip)
- Docker Compose:
```
services:
  qbit:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbit
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8084:8084
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./appdata:/config
    environment:
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=plex
```

**Application Info** (Don't skip)
- Container: lscr.io/linuxserver/qbittorrent:latest
[qbit_logs.txt](https://github.com/themepark-dev/theme.park/files/14826231/qbit_logs.txt)

**To Reproduce**
1. Click "Pause"
2. See error in console:  `QMetaObject::invokeMethod: No such method TorrentsController::stopAction()`

**Expected behavior**
To be able to stop the torrent.

**Additional context**
First I thought it's a bug with the qbit itself and I downgraded to 4.6.3 and after that to 4.6.2, but the issue was still present. I switched back to latest and recreated the container but I removed the docker mod and everything was fine.
