### ISSUE TITLE
Bazarr themes are no longer working after version 1.4.3

### ISSUE THREAD

**Issue by bassterror** [themepark-dev/theme.park#658]
Themes for bazarr are not working anymore. The last compatible version was 1.4.3. After that the themes are installed but are not working properly. Maybe some of the font colors and background are as they should be (in the main area of bazarr), but I'm not sure in that even. Buttons, sidebar, etc. - no longer following the chosen theme.

**Docker Compose**
```
services:
  bazarr_test:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr_test
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 6767:6767
    volumes:
      - ./appdata/bazarr:/config
      - /volume1/Plex:/Plex
    environment:
      - PUID=1026
      - PGID=101
      - TZ=Europe/Sofia
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:bazarr
      - TP_THEME=plex
networks:
  proxy:
    external: true
```
If you change image to ```image: lscr.io/linuxserver/bazarr:1.4.3```, you can see that the theme is showing correctly. 

At first I didn't noticed, because the theme "plex" that I use is not that different from the default dark theme of bazarr. Later I tested with different themes ("maroon" for example) and it really shows that it's not correctly applied. I also tried with hotio image, the result is the same.

**Screenshots**
incorrect:
![incorrect](https://github.com/user-attachments/assets/79c5a956-1247-4343-9e22-cf21dec7f50a)
![incorrect2](https://github.com/user-attachments/assets/9d77a788-397e-4a35-a720-cfb73c846523)

correct:
![correct](https://github.com/user-attachments/assets/1fa89ed6-e461-467f-bc80-6c3f3cfb6179)
![correct2](https://github.com/user-attachments/assets/d1c6fc71-4d35-4402-99cc-67bac9a32727)

**Log**
Nothing in the log shows failure.
[bazarr_test_logs.txt](https://github.com/user-attachments/files/17527509/bazarr_test_logs.txt)

**Bazarr Info**
- Version: 1.4.5 (same with 1.4.4 and everything else after including betas and latest beta 1.4.6-beta.11)
- Branch: latest
- Container: linuxserver and hotio
