### ISSUE TITLE
[PIHOLE] (aquamarine) Network tab empty/stuck on processing

### ISSUE THREAD

**Issue by Blexyel** [themepark-dev/theme.park#662]
**Describe the bug**
see title

**Theme Install Method** (Don't skip)
- overwrote lcars.css with aquamarine theme

**Application Info** (Don't skip)
- Pihole v5.18.3

**To Reproduce**
1. go to 'Tools'
2. click on 'Network'
3. see Network not load

**Expected behavior**
Have network load

**Screenshots**
![image](https://github.com/user-attachments/assets/14bdee20-f85b-4b83-8032-15f15b317459)

**Additional context**
These values are missing, causing the network tab to not load:

```css
.network-never {
  background-color: color;
}
.network-recent {
  background-color: color;
}
.network-old {
  background-color: color;
}
.network-older {
  background-color: color;
}
.network-gradient {
  background-image: linear-gradient(to right, color 0%, color 100%);
}
```

**Misc**
I would make a PR, but i dont know which values or whatever would be preferred, so issue it is.
